ALTER TABLE "bosses" ALTER COLUMN "hour" DROP NOT NULL;
ALTER TABLE "bosses" ALTER COLUMN "hour" DROP DEFAULT;
ALTER TABLE "bosses" ALTER COLUMN "minute" DROP NOT NULL;
ALTER TABLE "bosses" ALTER COLUMN "minute" DROP DEFAULT;
ALTER TABLE "bosses" ALTER COLUMN "clock_second" DROP NOT NULL;
ALTER TABLE "bosses" ALTER COLUMN "clock_second" DROP DEFAULT;
